# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/src"
    schedule:
      interval: daily
    versioning-strategy: auto
    # Allow up to 15 open pull requests for pip dependencies
    open-pull-requests-limit: 15
    allow:
      - dependency-type: "all"
