site_name: Client_API_VN
repo_url: https://github.com/dthonon/Client_API_VN
site_url: https://dthonon.github.io/Client_API_VN
site_description: This is a template repository for Python projects that use Poetry for their dependency management.
site_author: Daniel Thonon
edit_uri: edit/main/docs/
repo_name: dthonon/Client_API_VN
copyright: Maintained by <a href="https://dthonon.com">Daniel Thonon</a>.

nav:
  - Home: index.md
  - Applications:
      - Examples: apps/examples.md
      - transfer_vn: apps/transfer_vn.md
      - update_vn: apps/update_vn.md
      - validate_vn: apps/validate_vn.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "numpy"
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dthonon/Client_API_VN
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/Client_API_VN

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
